[package]
name = "basm"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "2"
either = "1"
num = "0.4.3"
thiserror = "1"

[profile.release]
lto = true
codegen-units = 1
