[package]
name = "basm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
colored = "2.1.0"
either = "1.13.0"
num = "0.4.3"
thiserror = "1.0.64"

[profile.release]
lto = true
codegen-units = 1
