[book]
authors = ["AtmolanderMimi"]
language = "en"
multilingual = false
src = "src"
title = "A Quick Introduction and Reference to Brain Aneurysm"

[output.html]
git-repository-url = "https://github.com/AtmolanderMimi/basm"
edit-url-template = "https://github.com/AtmolanderMimi/basm/tree/release/book/{path}"

[preprocessor.list-flags]
command = "python3 list-flags.py"
