[book]
authors = ["AtmolanderMimi"]
language = "en"
multilingual = false
src = "src"
title = "A Quick Introduction and Reference to Brain Aneurysm"

[preprocessor.list-flags]
command = "python3 list-flags.py"
